var ref = require('ref'),
    RefArray = require('ref-array'),
    Struct = require('ref-struct'),
    Union = require('ref-union'),
    _library = require('./../');

loadDependentSymbols();

_library._arg_separators = Struct({
    "input": ref.refType('char'),
    "output": ref.refType('char')
});

_library.arg_separators = _library._arg_separators;

_library._php_core_globals = Struct({
    "activated_auto_globals": RefArray('uchar', 8),
    "allow_url_fopen": 'uchar',
    "allow_url_include": 'uchar',
    "always_populate_raw_post_data": 'char',
    "arg_separator": _library.arg_separators,
    "auto_append_file": ref.refType('char'),
    "auto_globals_jit": 'uchar',
    "auto_prepend_file": ref.refType('char'),
    "connection_status": 'short',
    "disable_classes": ref.refType('char'),
    "disable_functions": ref.refType('char'),
    "display_errors": 'uchar',
    "display_startup_errors": 'uchar',
    "doc_root": ref.refType('char'),
    "docref_ext": ref.refType('char'),
    "docref_root": ref.refType('char'),
    "during_request_startup": 'uchar',
    "enable_dl": 'uchar',
    "enable_post_data_reading": 'uchar',
    "error_append_string": ref.refType('char'),
    "error_log": ref.refType('char'),
    "error_prepend_string": ref.refType('char'),
    "exit_on_timeout": 'uchar',
    "expose_php": 'uchar',
    "extension_dir": ref.refType('char'),
    "file_uploads": 'uchar',
    "header_is_being_sent": 'uchar',
    "html_errors": 'uchar',
    "http_globals": RefArray(ref.refType(_library.zval), 6),
    "ignore_repeated_errors": 'uchar',
    "ignore_repeated_source": 'uchar',
    "ignore_user_abort": 'short',
    "implicit_flush": 'uchar',
    "in_error_log": 'uchar',
    "in_user_include": 'uchar',
    "include_path": ref.refType('char'),
    "input_encoding": ref.refType('char'),
    "internal_encoding": ref.refType('char'),
    "last_error_file": ref.refType('char'),
    "last_error_lineno": 'int',
    "last_error_message": ref.refType('char'),
    "last_error_type": 'int',
    "log_errors": 'uchar',
    "log_errors_max_len": 'long',
    "mail_log": ref.refType('char'),
    "mail_x_header": 'uchar',
    "max_input_nesting_level": 'long',
    "max_input_time": 'long',
    "max_input_vars": 'long',
    "memory_limit": 'long',
    "modules_activated": 'uchar',
    "open_basedir": ref.refType('char'),
    "output_buffering": 'long',
    "output_encoding": ref.refType('char'),
    "output_handler": ref.refType('char'),
    "php_binary": ref.refType('char'),
    "register_argc_argv": 'uchar',
    "report_memleaks": 'uchar',
    "report_zend_debug": 'uchar',
    "request_order": ref.refType('char'),
    "rfc1867_protected_variables": _library.HashTable,
    "serialize_precision": 'long',
    "sql_safe_mode": 'uchar',
    "sys_temp_dir": ref.refType('char'),
    "tick_functions": _library.zend_llist,
    "track_errors": 'uchar',
    "unserialize_callback_func": ref.refType('char'),
    "upload_max_filesize": 'long',
    "upload_tmp_dir": ref.refType('char'),
    "user_dir": ref.refType('char'),
    "user_ini_cache_ttl": 'long',
    "user_ini_filename": ref.refType('char'),
    "variables_order": ref.refType('char'),
    "xmlrpc_error_number": 'long',
    "xmlrpc_errors": 'uchar'
});

_library._php_core_globals = Struct({
    "activated_auto_globals": RefArray('uchar', 8),
    "allow_url_fopen": 'uchar',
    "allow_url_include": 'uchar',
    "always_populate_raw_post_data": 'char',
    "arg_separator": _library.arg_separators,
    "auto_append_file": ref.refType('char'),
    "auto_globals_jit": 'uchar',
    "auto_prepend_file": ref.refType('char'),
    "connection_status": 'short',
    "disable_classes": ref.refType('char'),
    "disable_functions": ref.refType('char'),
    "display_errors": 'uchar',
    "display_startup_errors": 'uchar',
    "doc_root": ref.refType('char'),
    "docref_ext": ref.refType('char'),
    "docref_root": ref.refType('char'),
    "during_request_startup": 'uchar',
    "enable_dl": 'uchar',
    "enable_post_data_reading": 'uchar',
    "error_append_string": ref.refType('char'),
    "error_log": ref.refType('char'),
    "error_prepend_string": ref.refType('char'),
    "exit_on_timeout": 'uchar',
    "expose_php": 'uchar',
    "extension_dir": ref.refType('char'),
    "file_uploads": 'uchar',
    "header_is_being_sent": 'uchar',
    "html_errors": 'uchar',
    "http_globals": RefArray(ref.refType(_library.zval), 6),
    "ignore_repeated_errors": 'uchar',
    "ignore_repeated_source": 'uchar',
    "ignore_user_abort": 'short',
    "implicit_flush": 'uchar',
    "in_error_log": 'uchar',
    "in_user_include": 'uchar',
    "include_path": ref.refType('char'),
    "input_encoding": ref.refType('char'),
    "internal_encoding": ref.refType('char'),
    "last_error_file": ref.refType('char'),
    "last_error_lineno": 'int',
    "last_error_message": ref.refType('char'),
    "last_error_type": 'int',
    "log_errors": 'uchar',
    "log_errors_max_len": 'long',
    "mail_log": ref.refType('char'),
    "mail_x_header": 'uchar',
    "max_input_nesting_level": 'long',
    "max_input_time": 'long',
    "max_input_vars": 'long',
    "memory_limit": 'long',
    "modules_activated": 'uchar',
    "open_basedir": ref.refType('char'),
    "output_buffering": 'long',
    "output_encoding": ref.refType('char'),
    "output_handler": ref.refType('char'),
    "php_binary": ref.refType('char'),
    "register_argc_argv": 'uchar',
    "report_memleaks": 'uchar',
    "report_zend_debug": 'uchar',
    "request_order": ref.refType('char'),
    "rfc1867_protected_variables": _library.HashTable,
    "serialize_precision": 'long',
    "sql_safe_mode": 'uchar',
    "sys_temp_dir": ref.refType('char'),
    "tick_functions": _library.zend_llist,
    "track_errors": 'uchar',
    "unserialize_callback_func": ref.refType('char'),
    "upload_max_filesize": 'long',
    "upload_tmp_dir": ref.refType('char'),
    "user_dir": ref.refType('char'),
    "user_ini_cache_ttl": 'long',
    "user_ini_filename": ref.refType('char'),
    "variables_order": ref.refType('char'),
    "xmlrpc_error_number": 'long',
    "xmlrpc_errors": 'uchar'
});

_library.php_core_globals = _library._php_core_globals;

function loadDependentSymbols() {
    require('./../Zend/zend_hash.js');
    require('./../Zend/zend_llist.js');
};